version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: circular-word-chain
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["/bin/sh", "-lc", "php run.php; tail -f /dev/null"]
